[package]
name = "wsl2hosts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "*"
path-slash = "*"

[dependencies.windows]
version = "*"
features = [
    "Win32_System_Services",
    "Win32_Foundation",
    "Win32_Security",
]
